/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#005d63",
        "tertiary-fixed-dim": "#efc900",
        "surface-variant": "#25252c",
        "surface-dim": "#0e0e13",
        "on-tertiary-fixed": "#453900",
        "tertiary": "#ffe792",
        "secondary-fixed": "#f1c1ff",
        "surface-container-low": "#131318",
        "surface": "#0e0e13",
        "on-background": "#f8f5fd",
        "primary-fixed-dim": "#00deec",
        "surface-container": "#19191f",
        "inverse-surface": "#fbf8ff",
        "outline-variant": "#48474d",
        "error-container": "#a70138",
        "surface-bright": "#2c2b33",
        "inverse-primary": "#006a71",
        "secondary-fixed-dim": "#eaaeff",
        "secondary-container": "#9900cf",
        "secondary": "#d674ff",
        "outline": "#76747b",
        "secondary-dim": "#bb00fc",
        "tertiary-dim": "#efc900",
        "on-secondary-container": "#fff5fc",
        "inverse-on-surface": "#55545a",
        "on-tertiary-fixed-variant": "#665500",
        "on-error": "#490013",
        "on-surface-variant": "#acaab1",
        "primary": "#8ff5ff",
        "primary-fixed": "#00eefc",
        "tertiary-fixed": "#ffd709",
        "tertiary-container": "#ffd709",
        "on-secondary": "#390050",
        "on-secondary-fixed-variant": "#8400b3",
        "on-primary-fixed": "#003f43",
        "on-error-container": "#ffb2b9",
        "background": "#0e0e13",
        "on-tertiary-container": "#5b4b00",
        "primary-container": "#00eefc",
        "surface-container-lowest": "#000000",
        "primary-dim": "#00deec",
        "surface-tint": "#8ff5ff",
        "on-primary-container": "#005359",
        "on-primary-fixed-variant": "#005e64",
        "error": "#ff6e84",
        "on-surface": "#f8f5fd",
        "surface-container-high": "#1f1f26",
        "surface-container-highest": "#25252c",
        "on-tertiary": "#655400",
        "on-secondary-fixed": "#580079",
        "error-dim": "#d73357"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
